*** Variables ***
###     BUTTONS     ###
${loc_BUTTON_REJECT_EVERYTHING}                     //a[contains(.,'Reject everything')]
${loc_BUTTON_COTALOG}                               //*[@data-testid='category-tile']
${loc_BUTTON_DIALOG_CLOSE}                          //*[@id='alzaDialog']//*[@class='close']

${loc_LIST_ITEM_BOX}                                //*[contains(@class,'box browsingitem js-box canBuy inStockAvailability')]

${loc_LOADER_CONTAINER}                             //*[@class='circle-loader-container'][@style='display: none;']
